### ISSUE TITLE
Eucharitidae

### ISSUE THREAD

**Issue by JohnHeraty** [chalcid/outreach#10]
```
---
title: Family: Eucharitidae
date: 2018-12-07
modified: 2018-12-07
tags: ant,parasitoid, solenopsis, pheidole, fireant, wasmannia,chalcid,Eucharitidae
authors: John Heraty
family: Eucharitidae
distribution: worldwide 
top_image: https://sfg.taxonworks.org/s/4hu411
card_image: https://sfg.taxonworks.org/s/8th4hm/img_2_1.png
footer_image: 
layout: taxon_page
---
```

## Introduction

![Orasema sp.](https://sfg.taxonworks.org/s/4hu411)
##### _Orasema_ sp.

Where known, all Eucharitidae are parasitoids of the immature stages of ants. Eggs are laid away from the host, and the active first-instar larvae are transported back to the ant nest by foraging ant workers. Some adult members of the family have extreme modifications of the mesosoma that often include elongate mesoscutellar processes. Complex chemical interactions allow the adult wasps to escape from the ant nest, and some of the morphological modifications may be associated with being able to successfully escape without damage to the body or wings. 

## Biology 

![_Pseudochalcura_ _gibbosa_: A, _ovipositing into _Salix_; B&C, eggs in _Rhododendron_ bud](https://sfg.taxonworks.org/s/411qkh)
##### _Pseudochalcura  gibbosa_: A, ovipositing into _Salix_; B&C, eggs in _Rhododendron_ bud

Eggs are deposited onto or in plant tissue away from the host, and the mobile, sclerotized first-instar planidium that is responsible for gaining access to the ant nest. Foraging ants act as vectors to move the plandia into the ant colony. Planidia are likely transported by the ants in their infrabuccal pouch, and then transferred through trophyllaxis or by some other means to the host larva. In the nest, the planidium first attacks the host ant larva, but must complete its development on the host pupa. In Gollumiellinae, Oraseminae, and _Pseudometagea_ (Eucharitinae), the planidium burrows into the larval host and begins to feed and expand in size. In other Eucharitinae, the planidium feeds very little and remains attached to the external surface of their larval host. Upon pupation of the host, the planidium migrates to the ventral region of the host thorax. Development is completed on the host pupa, usually with only one parasitoid per host, but with as many as three per host if the host pupa is large enough. It is unlikely that parasitoids feed on more than one host. Both Gollumiellinae and Oraseminae develop on ants without a cocoon, whereas all Eucharitinae attack ants that pupate within a cocoon. Thus, pupation by the eucharitid is either within the open brood pile of ants without a cocoon, or within the cocoon of ants that have one. Escape from the ant nest may involve sequestration of cuticular hydrocarbons from the surrounding brood.

## Economic Importance

Eucharitidae can be both beneficial and potentially harmful in different systems. _Orasema_ _minutissima_ has been proposed as potential biological control agent of Wasmannia auropunctata, and _Orasema_ _xanthopus_ has been proposed as potential biological control agent of _Solenopsis_ _invicta_ and _S. richteri_. _Orasema minutissima_ attack both _Wasmannia_ and _Pheidole_. Both ant genera, and often Myrmicinae in general, are often introduced and invasive on islands, and thus the successful introduction of _Orasema_ would be beneficial and would not impact any native ants in other subfamilies. Control of imported fire ants on continental landmasses is more difficult, as control is likely not to be effective in areas where control is desired (urban areas and pasturelands) when compared to their native habitat in Argentina and Brazil. One species, _Orasema taii_ may have been responsible for the decline of a native _Solenopsis geminata_ x _xyloni_ hybrid in Texas by differentially attacking it and not the invasive _S. invicta_. The greatest obstacle to their potential for biological control is the difficulty in rearing both the parasitoid and host prior to any release.

## Links

* [_Orasema simulatrix_ planidia](https://www.youtube.com/watch?v=pBnwjW2Eg2A)
* [_Orasema_ _wayqecha_ planidia](https://www.youtube.com/watch?v=ZXAWrdrDZ40)
* [_Schizaspidia_ male on leaf](https://www.youtube.com/watch?v=4CmQxOtGWdk)

**Comment by JohnHeraty** [comment]
I can't see the figure legend that I added (see my 'written' attempt)- can a legend be attached to a picture underneath?

**Comment by JohnHeraty** [comment]
and please add to the diversity page

**Comment by mjy** [comment]
@JohnHeraty The text for figures you provided is the alternate text when the image is not there.  There is no figure caption Markdown per-se, so I used a small heading (`#####`) , it seems to work OK.
